import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import cm

REPORTS_DIR = "reports/exports"
os.makedirs(REPORTS_DIR, exist_ok=True)


def _safe_name(product: str) -> str:
    return product.lower().strip().replace(" ", "_")


def generate_html(product: str, data: dict) -> str:
    safe = _safe_name(product)
    path = os.path.join(REPORTS_DIR, f"{safe}_report.html")
    timestamp = datetime.now().strftime("%B %d, %Y %I:%M %p")

    severity = data.get("severity_score", 0)
    sentiment = data.get("overall_sentiment", "mixed")
    sentiment_color = {
        "positive": "#22c55e",
        "negative": "#ef4444",
        "mixed":    "#2c28ae"
    }.get(sentiment, "#f59e0b")

    key_points  = "".join(f"<li>{p}</li>" for p in data.get("key_points", []))
    action_items = "".join(f"<li>{a}</li>" for a in data.get("action_items", []))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ORCHA Report — {product}</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family:'Segoe UI',sans-serif; background:#f8fafc; color:#1e293b; padding:40px; }}
        .container {{ max-width:800px; margin:0 auto; background:white; border-radius:16px; padding:48px; box-shadow:0 4px 24px rgba(0,0,0,0.08); }}
        .badge {{ display:inline-block; background:#6366f1; color:white; padding:4px 12px; border-radius:999px; font-size:12px; font-weight:600; letter-spacing:1px; margin-bottom:12px; }}
        h1 {{ font-size:28px; font-weight:700; margin-bottom:8px; }}
        .meta {{ font-size:13px; color:#94a3b8; margin-bottom:24px; }}
        .verdict {{ background:#f8fafc; border-left:4px solid #6366f1; padding:16px 20px; border-radius:8px; margin:24px 0; font-size:15px; font-style:italic; color:#475569; }}
        .stats {{ display:flex; gap:16px; margin:24px 0; }}
        .stat {{ flex:1; background:#f8fafc; border-radius:12px; padding:16px; text-align:center; }}
        .stat-value {{ font-size:28px; font-weight:700; }}
        .stat-label {{ font-size:12px; color:#94a3b8; margin-top:4px; }}
        h2 {{ font-size:16px; font-weight:600; margin:28px 0 12px; color:#374151; }}
        ul {{ padding-left:20px; }}
        li {{ margin-bottom:8px; font-size:14px; line-height:1.6; color:#475569; }}
        .summary {{ font-size:14px; line-height:1.8; color:#475569; }}
        .footer {{ margin-top:40px; padding-top:20px; border-top:1px solid #f1f5f9; font-size:12px; color:#94a3b8; text-align:center; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="badge">ORCHA REPORT</div>
        <h1>{product.title()}</h1>
        <div class="meta">Generated on {timestamp}</div>
        <div class="verdict">"{data.get('verdict', 'No verdict available')}"</div>
        <div class="stats">
            <div class="stat">
                <div class="stat-value" style="color:{sentiment_color}">{sentiment.title()}</div>
                <div class="stat-label">Overall Sentiment</div>
            </div>
            <div class="stat">
                <div class="stat-value" style="color:#6366f1">{severity}/10</div>
                <div class="stat-label">Severity Score</div>
            </div>
        </div>
        <h2>Key Points</h2>
        <ul>{key_points}</ul>
        <h2>Action Items</h2>
        <ul>{action_items}</ul>
        <h2>Executive Summary</h2>
        <div class="summary">{data.get('final_summary', '')}</div>
        <div class="footer">Generated by ORCHA — AI Multi-Agent Product Feedback Analyst</div>
    </div>
</body>
</html>"""

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)

    return path


def generate_pdf(product: str, data: dict) -> str:
    safe = _safe_name(product)
    path = os.path.join(REPORTS_DIR, f"{safe}_report.pdf")
    timestamp = datetime.now().strftime("%B %d, %Y %I:%M %p")

    # colors
    purple  = HexColor("#6366f1")
    muted   = HexColor("#94a3b8")
    dark    = HexColor("#1e293b")
    body    = HexColor("#475569")

    # styles
    styles  = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "title", fontSize=22, textColor=dark,
        fontName="Helvetica-Bold", spaceAfter=6
    )
    meta_style = ParagraphStyle(
        "meta", fontSize=10, textColor=muted,
        fontName="Helvetica", spaceAfter=16
    )
    badge_style = ParagraphStyle(
        "badge", fontSize=10, textColor=purple,
        fontName="Helvetica-Bold", spaceAfter=8,
        letterSpacing=1
    )
    verdict_style = ParagraphStyle(
        "verdict", fontSize=12, textColor=body,
        fontName="Helvetica-Oblique", spaceAfter=16,
        leftIndent=12, borderPadding=10
    )
    heading_style = ParagraphStyle(
        "heading", fontSize=13, textColor=dark,
        fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=8
    )
    body_style = ParagraphStyle(
        "body", fontSize=11, textColor=body,
        fontName="Helvetica", spaceAfter=6, leading=16
    )
    stat_style = ParagraphStyle(
        "stat", fontSize=14, textColor=purple,
        fontName="Helvetica-Bold", spaceAfter=4
    )

    # build content
    sentiment = data.get("overall_sentiment", "mixed")
    severity  = data.get("severity_score", 0)

    content = []

    content.append(Paragraph("ORCHA REPORT", badge_style))
    content.append(Paragraph(product.title(), title_style))
    content.append(Paragraph(f"Generated on {timestamp}", meta_style))
    content.append(Spacer(1, 0.3 * cm))

    content.append(Paragraph(
        f'"{data.get("verdict", "No verdict available")}"', verdict_style
    ))
    content.append(Spacer(1, 0.3 * cm))

    content.append(Paragraph(f"Sentiment: {sentiment.title()}", stat_style))
    content.append(Paragraph(f"Severity Score: {severity}/10", stat_style))
    content.append(Spacer(1, 0.3 * cm))

    content.append(Paragraph("Key Points", heading_style))
    for point in data.get("key_points", []):
        content.append(Paragraph(f"• {point}", body_style))

    content.append(Paragraph("Action Items", heading_style))
    for item in data.get("action_items", []):
        content.append(Paragraph(f"• {item}", body_style))

    content.append(Paragraph("Executive Summary", heading_style))
    content.append(Paragraph(data.get("final_summary", ""), body_style))

    content.append(Spacer(1, 1 * cm))
    content.append(Paragraph(
        "Generated by ORCHA — AI Multi-Agent Product Feedback Analyst",
        ParagraphStyle("footer", fontSize=9, textColor=muted, fontName="Helvetica")
    ))

    # build PDF
    doc = SimpleDocTemplate(
        path, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )
    doc.build(content)

    return path